common:
  namespace: keycloak

config:
  databaseHost: openproject-id-postgresql
  databaseName: keycloak
  databaseUser: keycloak
  defaultRealm: master

image:
  name: openproject/openproject-id:26.3.3-dev
  pullPolicy: IfNotPresent

ingress:
  annotations:
  class: nginx
  host: keycloak.k8s.local

scaling:
  replicaCount: 1
  cpuRequest: 0.6
  memoryRequest: 768Mi
  memoryLimit: 3Gi
  hpa:
    enabled: false

secrets:
  create: true
  name: keycloak
  data:
    adminPassword: "change-me-1234!"
    databasePassword: shouldBeMoreSecureThanThis

service:
  annotations:

postgresql:
  create: true
  namespaceOverride: keycloak
  auth:
    postgresPassword: ""
    username: keycloak
    password: "shouldBeMoreSecureThanThis"
    database: keycloak
  architecture: standalone
