apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.common.namespace | quote }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
spec:
  {{- if not .Values.scaling.hpa.enabled }}
  replicas: {{ .Values.scaling.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: keycloak
      app.kubernetes.io/part-of: keycloak
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  # maxUnavailable and maxSurge above and minReadySeconds below should ensure that deployments happen sufficiently slowly, so that
  # the cache can be redistributed across nodes, even during deployments. We only replace one pod at a time.
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/component: keycloak
        app.kubernetes.io/part-of: keycloak
    spec:
      containers:
      - name: keycloak
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/opt/keycloak/bin/kc.sh", "start"]
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: admin-password
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL_HOST
          value: {{ .Values.config.databaseHost }}
        - name: KC_DB_URL_DATABASE
          value: {{ .Values.config.databaseName }}
        - name: KC_DB_USERNAME
          value: "{{ .Values.config.databaseUser }}"
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: database-password
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_PROXY_HEADERS
          value: xforwarded
        - name: KC_HOSTNAME
          value: "https://{{ .Values.ingress.host }}"
        - name: KC_SPI_THEME_WELCOME_THEME
          value: "openproject"
        - name: DEFAULT_REALM
          value: {{ .Values.config.defaultRealm }}
        resources:
          requests:
            cpu: "{{ .Values.scaling.cpuRequest }}"
            memory: "{{ .Values.scaling.memoryRequest }}"
          limits:
            memory: "{{ .Values.scaling.memoryLimit }}"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /realms/master
            port: http
            scheme: HTTP
