
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: {{ .Values.common.namespace | quote }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
spec:
  ingressClassName: {{ .Values.ingress.class | quote }}
  rules:
  - host: {{ (tpl .Values.ingress.host .) | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              name: http
