apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: openproject-id
    app.kubernetes.io/managed-by: helm
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: keycloak
      app.kubernetes.io/part-of: openproject-id
