apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: keycloak
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: keycloak
      app.kubernetes.io/part-of: keycloak
