
{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.common.namespace | quote }}
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/part-of: openproject-id
    app.kubernetes.io/managed-by: helm
type: Opaque
stringData:
  admin-password: {{ .Values.secrets.data.adminPassword }}
  database-user: {{ .Values.secrets.data.databaseUser }}
  database-password: {{ .Values.secrets.data.databasePassword }}
{{- end }}
