annotations:
  images: |
    - name: keycloak
      image: quay.io/keycloak/keycloak:26.3.3
apiVersion: v2
appVersion: 26.3.3
maintainers:
- name: OpenProject
  url: https://github.com/opf/
name: OpenProject ID
version: 1.0
